name: CI PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar o PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Dar permissão de execução para o PHPUnit
      run: chmod +x vendor/bin/phpunit

    - name: Instalar dependências do Composer
      run: composer install --no-interaction --prefer-dist

    - name: Rodar testes com PHPUnit
      run: vendor/bin/phpunit tests/
